#:kivy 2.0.0

#:include source/app/global.kv

<SearchScreen>:
    results: results
    searched_word: searched_word
    BoxLayout:
        orientation: 'vertical'
        TextInput:
            id: searched_word
            multiline: False
            size_hint_y: 1
            text: ''
        ScrollView:
            size_hint_y: 9
            BoxLayout:
                id: results
                orientation: 'vertical'
                size_hint_y: None